# Generated by Django 5.1.3 on 2026-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(help_text='Price in cents (e.g. 2499 = $24.99)')),
                ('format', models.CharField(choices=[('lp', 'LP'), ('ep', 'EP'), ('7inch', '7"')], default='lp', max_length=10)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
